# Generated by Django 5.0.4 on 2024-07-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
